name: Assign Chapter
description: Assign a chapter for creating a markdown file for a specific lesson.
title: "Title"
labels: [documentation]
body:

  - type: input
    id: chapter_name
    attributes:
      label: "Description"
      description: "Enter the chapter name and link."
      value: "We need to create markdown for [chapter_name](chapter_link)"

  - type: textarea
    id: pdf
    attributes:
      label: "Tamil and English Lesson pdf"
      placeholder: "upload the PDF or drag and drop"
