name: Assign Chapter to Developer
description: Assign a chapter to a developer for creating a markdown file for a specific lesson.
title: "{{ title }}"  # Title of the lesson
labels: [documentation]
body:
  - type: input
    id: title
    attributes:
      label: "Lesson Title"
      description: "Enter the title of the lesson (this will be the issue title)."
      placeholder: "e.g., Probability Distributions"
      required: true

  - type: markdown
    attributes:
      value: |
        **Task Description**: We need to create a markdown file for the lesson.

  - type: input
    id: chapter_name
    attributes:
      label: "Chapter Name"
      description: "Enter the name of the chapter (this will be used in the static message)."
      placeholder: "e.g., Probability Distributions"
      required: true

  - type: input
    id: chapter_url
    attributes:
      label: "Chapter URL"
      description: "Enter the URL for the lesson/chapter."
      placeholder: "e.g., https://github.com/tnebooks/repo/tree/main/content.en/lesson_name"
      required: true

  - type: markdown
    attributes:
      value: |
        We need to create a markdown file for [{{ chapter_name }}]({{ chapter_url }})

  - type: input
    id: tamil_pdf
    attributes:
      label: "Tamil PDF Link"
      description: "Provide the link to the Tamil version of the PDF."
      placeholder: "e.g., https://example.com/tamil-pdf"
      required: true

  - type: input
    id: english_pdf
    attributes:
      label: "English PDF Link"
      description: "Provide the link to the English version of the PDF."
      placeholder: "e.g., https://example.com/english-pdf"
      required: true
